 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nba;


import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class jRosterMenuProceed extends javax.swing.JFrame {
    private btnPressedStored btnStored;    
    private BtnInjuryOrRoster btnInjuryRoster = new BtnInjuryOrRoster();
    
    public jRosterMenuProceed(btnPressedStored btnStored, BtnInjuryOrRoster btnInjuryRoster) {           
        initComponents();
        setImageMethod("src\\icons\\nbaLogo.png", nbaLogo);
        setImageMethod("src\\icons\\basketballCourt.png", icon);
        this.btnStored = btnStored;     
        this.btnInjuryRoster = btnInjuryRoster;
    }   
    
    public jRosterMenuProceed() {           
        initComponents();
        setImageMethod("src\\icons\\nbaLogo.png", nbaLogo);
        setImageMethod("src\\icons\\basketballCourt.png", icon);    
    }
    
    public void setImageMethod(String imagePath, JLabel labelName) {
        ImageIcon icon = new ImageIcon(imagePath);
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        labelName.setIcon(scaledIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSide = new javax.swing.JPanel();
        nbaLogo = new javax.swing.JLabel();
        panelCentre = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        instruction = new javax.swing.JTextArea();
        btnBefore = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        proceedTitle = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelSide.setBackground(new java.awt.Color(255, 51, 0));
        panelSide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nbaLogo.setText("nba");
        panelSide.add(nbaLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, 150));

        getContentPane().add(panelSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 110, 760));

        panelCentre.setBackground(new java.awt.Color(0, 0, 153));

        instruction.setEditable(false);
        instruction.setBackground(new java.awt.Color(0, 0, 0));
        instruction.setColumns(20);
        instruction.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        instruction.setForeground(new java.awt.Color(255, 255, 255));
        instruction.setRows(5);
        instruction.setText("\t     Welcome to choose your roster member!!!\n\n       Please read the below instructions carefully......\n\n      1. Your roster must consist a minimum of 10 players \n          and a maximum of 15 players.\n\n      2. Your roster must have at least 2 Guard, Forward, Centre.\n\n      3. Superstar player' salary is 3000 while \n          non-Superstar player's salary is 1000.\n\n      4. Your roster total salary should not exceed 20000.\n\n      5. Build your roster wisely based on these conditions.\n\n      6. You are encouraged to view the candidate list before you select player.\n");
        jScrollPane2.setViewportView(instruction);

        btnBefore.setText("Back");
        btnBefore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeforeActionPerformed(evt);
            }
        });

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        proceedTitle.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        proceedTitle.setText("View Roster");

        icon.setText("icon");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(proceedTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(icon, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(proceedTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelCentreLayout = new javax.swing.GroupLayout(panelCentre);
        panelCentre.setLayout(panelCentreLayout);
        panelCentreLayout.setHorizontalGroup(
            panelCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCentreLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelCentreLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panelCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCentreLayout.createSequentialGroup()
                        .addComponent(btnBefore, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCentreLayout.setVerticalGroup(
            panelCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCentreLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBefore, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        getContentPane().add(panelCentre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBeforeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeforeActionPerformed
        dispose();
        new jRosterMenu().setVisible(true);
    }//GEN-LAST:event_btnBeforeActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        String lastBtn = btnStored.getBtnPressed();
        dispose();
        
        switch(lastBtn) {
            case "View" -> new jViewRoster(btnInjuryRoster).setVisible(true);
            case "Add" -> new jAddPlayer().setVisible(true);
            case "Remove" -> new jRemovePlayer().setVisible(true);
            default -> JOptionPane.showMessageDialog(jRosterMenuProceed.this, "Unknown Button Pressed", "Error!",  JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jRosterMenuProceed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jRosterMenuProceed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jRosterMenuProceed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jRosterMenuProceed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jRosterMenuProceed().setVisible(true);
            }
        });
    }
    
    public javax.swing.JTextArea getInstruction() {
        return instruction;
    }    
    
    public javax.swing.JLabel getProceedTitle() {
        return proceedTitle;
    }
    
    public javax.swing.JLabel getIcon() {
        return icon;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBefore;
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel icon;
    private javax.swing.JTextArea instruction;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nbaLogo;
    private javax.swing.JPanel panelCentre;
    private javax.swing.JPanel panelSide;
    private javax.swing.JLabel proceedTitle;
    // End of variables declaration//GEN-END:variables
}
