/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nba_gmanager;



/**
 *
 * @author ziyuan
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ranking = new javax.swing.JButton();
        DynamicSearching = new javax.swing.JButton();
        GameSchedule = new javax.swing.JButton();
        ActiveRoster = new javax.swing.JButton();
        Injuries = new javax.swing.JButton();
        Contract = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ranking.setBackground(new java.awt.Color(255, 153, 153));
        Ranking.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        Ranking.setForeground(new java.awt.Color(0, 0, 0));
        Ranking.setText(">");
        Ranking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RankingActionPerformed(evt);
            }
        });
        getContentPane().add(Ranking, new org.netbeans.lib.awtextra.AbsoluteConstraints(735, 115, -1, -1));

        DynamicSearching.setBackground(new java.awt.Color(255, 153, 153));
        DynamicSearching.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        DynamicSearching.setForeground(new java.awt.Color(0, 0, 0));
        DynamicSearching.setText(">");
        DynamicSearching.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DynamicSearchingActionPerformed(evt);
            }
        });
        getContentPane().add(DynamicSearching, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 510, -1, -1));

        GameSchedule.setBackground(new java.awt.Color(255, 153, 153));
        GameSchedule.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        GameSchedule.setForeground(new java.awt.Color(0, 0, 0));
        GameSchedule.setText(">");
        GameSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GameScheduleActionPerformed(evt);
            }
        });
        getContentPane().add(GameSchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 525, -1, -1));

        ActiveRoster.setBackground(new java.awt.Color(255, 153, 153));
        ActiveRoster.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        ActiveRoster.setForeground(new java.awt.Color(0, 0, 0));
        ActiveRoster.setText(">");
        ActiveRoster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActiveRosterActionPerformed(evt);
            }
        });
        getContentPane().add(ActiveRoster, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 780, -1, -1));

        Injuries.setBackground(new java.awt.Color(255, 153, 153));
        Injuries.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        Injuries.setForeground(new java.awt.Color(0, 0, 0));
        Injuries.setText(">");
        Injuries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InjuriesActionPerformed(evt);
            }
        });
        getContentPane().add(Injuries, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 780, -1, -1));

        Contract.setBackground(new java.awt.Color(255, 153, 153));
        Contract.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        Contract.setForeground(new java.awt.Color(0, 0, 0));
        Contract.setText(">");
        Contract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContractActionPerformed(evt);
            }
        });
        getContentPane().add(Contract, new org.netbeans.lib.awtextra.AbsoluteConstraints(855, 780, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Untitled (1).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 950));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RankingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RankingActionPerformed

    private void DynamicSearchingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DynamicSearchingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DynamicSearchingActionPerformed

    private void GameScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GameScheduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GameScheduleActionPerformed

    private void ActiveRosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActiveRosterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ActiveRosterActionPerformed

    private void InjuriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InjuriesActionPerformed
        // TODO add your handling code here:
        InjuryPlayer injuryPlayer = new InjuryPlayer();
        injuryPlayer.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_InjuriesActionPerformed

    private void ContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContractActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContractActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActiveRoster;
    private javax.swing.JButton Contract;
    private javax.swing.JButton DynamicSearching;
    private javax.swing.JButton GameSchedule;
    private javax.swing.JButton Injuries;
    private javax.swing.JButton Ranking;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
